description: Apps and Engines showing when an engine is launched with a project only
  context.
engines:
  tk-desktop:
    apps: {tk-multi-launchhiero: '@launch_hiero', tk-multi-launchmaya: '@launch_maya',
      tk-multi-launchnuke: '@launch_nuke', tk-shotgun-launchphotoshop: '@launch_photoshop',
      tk-multi-launchhoudini: '@launch_houdini'}
    collapse_rules:
    - {button_label: $app, match: Launch $app $version, menu_label: Launch $version}
    debug_logging: true
    default_group: Studio
    groups: []
    hook_launch_python: default
    location:
      version: v2.0.21
      type: app_store
      name: tk-desktop
    show_recents: true
  tk-hiero:
    apps:
      tk-hiero-export:
        audio_published_file_type: Hiero Audio
        custom_template_fields: []
        default_task_filter: '[[''step.Step.code'', ''is'', ''Comp'']]'
        default_task_template: Basic shot template
        hook_get_extra_publish_data: default
        hook_get_quicktime_settings: default
        hook_get_shot: '{config}/hiero_export/axis_hiero_get_shot.py'
        hook_post_version_creation: default
        hook_pre_export: default
        hook_resolve_custom_strings: default
        hook_translate_template: default
        hook_update_version_data: default
        hook_upload_thumbnail: default
        location:
          version: v0.3.19
          type: app_store
          name: tk-hiero-export
        nuke_script_published_file_type: Nuke Script
        nuke_script_toolkit_write_nodes:
        - {channel: stereoexr32, name: 'Stereo Exr, 32 bit'}
        - {channel: stereoexr16, name: 'Stereo Exr, 16 bit'}
        - {channel: monodpx, name: Mono Dpx}
        plate_published_file_type: Hiero Plate
        template_nuke_script_path: hiero_nuke_script
        template_plate_path: hiero_plate_path
        template_render_path: hiero_render_path
        template_version: hiero_version
      tk-hiero-openinshotgun:
        location:
          version: v0.3.3
          type: app_store
          name: tk-hiero-openinshotgun
      tk-multi-about: '@about'
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.6.1}
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      tk-multi-workfiles2:
        allow_task_creation: true
        create_new_task_hook: '{self}/create_new_task.py'
        custom_actions_hook: '{self}/custom_actions.py'
        entities:
        - caption: Assets
          entity_type: Task
          filters:
          - [entity, type_is, Asset]
          hierarchy: [entity.Asset.sg_asset_type, entity, step, content]
        - caption: Shots
          entity_type: Task
          filters:
          - [entity, type_is, Shot]
          hierarchy: [entity.Shot.sg_sequence, entity, step, content]
        file_extensions: []
        hook_copy_file: '{self}/copy_file.py'
        hook_filter_publishes: '{self}/filter_publishes.py'
        hook_filter_work_files: '{self}/filter_work_files.py'
        hook_scene_operation: '{self}/scene_operation_tk-hiero.py'
        launch_at_startup: true
        location:
          version: v0.7.39
          type: app_store
          name: tk-multi-workfiles2
        my_tasks_extra_display_fields: []
        saveas_default_name: scene
        saveas_prefer_version_up: false
        show_my_tasks: true
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
        version_compare_ignore_fields: []
    bin_context_menu:
    - {app_instance: tk-multi-workfiles2, keep_in_menu: false, name: File Save...,
      requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    debug_logging: true
    location: {name: tk-hiero, type: app_store, version: v0.2.5}
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-shotgunpanel:
        action_mappings:
          PublishedFile:
          - actions: [publish_clipboard]
            filters: {}
          - actions: [reference, import]
            filters: {published_file_type: Maya Scene}
          - actions: [texture_node]
            filters: {published_file_type: Rendered Image}
          - actions: [texture_node]
            filters: {published_file_type: Photoshop Image}
          - actions: [udim_texture_node]
            filters: {published_file_type: UDIM Image}
          - actions: [reference]
            filters: {published_file_type: Geometry}
          - actions: [reference]
            filters: {published_file_type: Camera}
          Task:
          - actions: [assign_task, task_to_ip]
            filters: {}
          Version:
          - actions: [play_in_rv]
            filters: {}
        actions_hook: '{self}/tk-maya_actions.py:{config}/panel/maya_actions.py'
        location:
          version: v1.2.7
          type: app_store
          name: tk-multi-shotgunpanel
        shotgun_fields_hook: '{self}/shotgun_fields.py'
      tk-multi-workfiles2: '@workfiles2'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.6.0
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    template_project:
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps: {tk-multi-about: '@about', tk-multi-screeningroom: '@launch_screeningroom',
      tk-multi-workfiles: '@workfiles'}
    bin_context_menu: []
    compatibility_dialog_min_version: 8
    debug_logging: false
    favourite_directories: []
    location:
      version: v0.6.9
      type: app_store
      name: tk-nuke
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    spreadsheet_context_menu: []
    timeline_context_menu: []
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps: {tk-multi-about: '@about', tk-multi-screeningroom: '@launch_screeningroom',
      tk-multi-workfiles: '@workfiles'}
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.3.3}
  tk-shell:
    apps: {tk-multi-launchhiero: '@launch_hiero', tk-multi-launchmaya: '@launch_maya',
      tk-multi-launchnuke: '@launch_nuke', tk-shotgun-launchphotoshop: '@launch_photoshop'}
    debug_logging: false
    location:
      version: v0.5.0
      type: app_store
      name: tk-shell
  tk-houdini:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles2: '@workfiles2'
    template_project:
    use_sgtk_as_menu_name: false
    location:
      version: v1.0.10
      type: app_store
      name: tk-houdini
    enable_sg_shelf: true
    enable_sg_menu: true
    debug_logging: false
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-publish, name: Publish...}
frameworks:
  tk-framework-adminui_v0.x.x:
    location:
      version: v0.1.6
      type: app_store
      name: tk-framework-adminui
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.2.2}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
includes: [./includes/app_launchers.yml, ./includes/common_apps.yml]
